name: Monthly Dependency Update

on:
  schedule:
    - cron: '0 0 1 * *' # Runs monthly, first day of month

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Update dependencies
        run: |
          npm install -g npm-check-updates
          ncu -u
          npm install
      - name: Check for changes
        id: git_diff
        run: |
          git diff --exit-code package.json || echo "changed=true" >> $GITHUB_OUTPUT
      - name: Create PR if changed
        if: steps.git_diff.outputs.changed == 'true'
        run: |
          git checkout -b chore/update-deps-$(date +'%Y-%m')
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add package.json package-lock.json
          git commit -m "chore: monthly dependency update"
          git push origin HEAD
          gh pr create --title "Monthly dependency update" --body "Automated update of dependencies in package.json" --base main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
