name: Release Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - entrypoint.sh
      - marp-engine.js
      - package.json

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          VERSION=$(cat package.json | jq -r .version)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/marp-plus-cli:${VERSION} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/marp-plus-cli:${VERSION}
